spring.application.name=springboot-swagger-demo
server.port=8080

# Swagger UI configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.api-docs.path=/v3/api-docs
